version: '3.8'

services:
  web:
    build:
       context: ./services/api
    command: gunicorn main:app --bind 0.0.0.0:5000 -k uvicorn.workers.UvicornWorker
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    expose:
      - 5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"

  traefik:
    image: traefik:v2.10.7
    ports:
      - "81:81"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$PWD/services/traefik/traefik.dev.toml:/etc/traefik/traefik.toml"
